name: pocketbase_utils
description: "pocketbase_utils is a dart library that generates Dart models code from a PocketBase collections scheme json file."
version: 0.1.6
repository: https://github.com/utopicnarwhal/pocketbase_utils

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ">=7.0.0 <9.0.0"
  args: ^2.7.0
  code_builder: ^4.11.0
  collection: ^1.19.1
  dart_style: ^3.0.1
  json_annotation: ^4.9.0
  path: ^1.9.1
  petitparser: ">=4.0.0 <8.0.0"
  yaml: ^3.1.3
  recase: ^4.1.0
  diacritic: ^0.1.6

dev_dependencies:
  very_good_analysis: ^9.0.0

  build_runner: ^2.10.3
  json_serializable: ^6.11.1
  lints: ^6.0.0

executables:
  pbutil-gen: generate

pocketbase_utils:
  enabled: true # Required. Must be set to true to activate the package. Default: false
  pb_schema_path: pb_schema.json # Optional. Sets the path of your collection schema file. Default: pb_schema.json
  output_dir: output_generated # Optional. Sets the directory of generated model files. If the directory doesn't exist â€” it'll be created. Default: lib/generated/pocketbase
  line_length: 80 # Optional. Sets the length of line for dart formatter of generated code. Default: 80
  generate_system_collections: false # Optional. Generate models for the system level collections like `_mfas`, `_otps`, and `_superusers`. Default: false

